import re

ROOTS_REGEX = re.compile(
	r"Some roots lie here waiting to ensnare weary travellers\.|"
	r"The remains of a clump of roots lie here in a heap of rotting compost\.|"
	r"A clump of roots is here, fighting|"
	r"Some withered twisted roots writhe towards you\.|"
	r"Black roots shift uneasily all around you\.|"
	r"black tangle of roots|"
	r"Massive roots shift uneasily all around you\."
)

MOB_FLAGS = (
	# in gui: guild, quest, rent, shop, aggressive
	"rent",
	"shop",
	"weapon_shop",
	"armour_shop",
	"food_shop",
	"pet_shop",
	"guild",
	"scout_guild",
	"mage_guild",
	"cleric_guild",
	"warrior_guild",
	"ranger_guild",
	"aggressive_mob", # almost everything...
	"quest_mob",
	"passive_mob",
	"elite_mob", # a dozen mobs
	"super_mob", # 4 rooms
	"milkable",
	"rattlesnake",
	"roots",
)

LOAD_FLAGS = (
	# in gui: attention, armour, herb, key, treasure, weapon
	"treasure",
	"armour",
	"weapon",
	"water",
	"food",
	"herb",
	"key",
	"mule",
	"horse",
	"pack_horse",
	"trained_horse",
	"rohirrim",
	"warg",
	"boat",
	"attention",
	"tower",  # Player can 'watch' surrounding rooms from this one.
	"clock",
	"mail",
	"stable",
	"white_word",
	"dark_word",
	"equipment",
	"coach",
	"ferry",
)

INGREDIENTS_FLAGS = (
	'acorns',
	'albino salamander',
	'anemone',
	'antidote',
	'apple',
	'athelas',
	'baneberries',
	'belladonna',
	'blackberries',
	'blackcurrant',
	'blackflower',
	'blackthorn',
	'bluebells',
	'blueberries',
	'blueberry',
	'bright red mushroom',
	'bulrushes',
	'buttercups',
	'cardamom',
	'cherries',
	'cinnamon',
	'clover',
	'comfrey',
	'coneflower',
	'conkers',
	'coriander',
	'darkflower',
	'dark-green moss',
	'egg',
	'elderberries',
	'figwort',
	'flour',
	'forget-me-nots',
	'fosforescent moss',
	'foxglove',
	'foxtail',
	'ginseng',
	'goosegrass',
	'hawkweed',
	'hawthorn berries',
	'heather',
	'hemlock',
	'hithlain',
	'hollyberries',
	'honey',
	'honeycomb',
	'honeysuckle',
	'inkberries',
	'ivory rose',
	'juniper',
	'lily',
	'marjoram',
	'mauve petals',
	'mint',
	'mistletoe',
	'moss',
	'nettle',
	'orchid',
	'paprika',
	'pepper',
	'phosphorescent moss',
	'pipe-weed',
	'pipeweed',
	'poppy',
	'putrid fungus',
	'ragwort',
	'raspberries',
	'rattlesnake',
	'red mushroom',
	'red rose',
	'reed',
	'rose',
	'rosemary',
	'sage',
	'salamander',
	'salt',
	'sickly green mushroom',
	'simbelmyne',
	'strawberries',
	'tarragon',
	'thistles',
	'thyme',
	'valerian',
	'violet orchid',
	'water-lily',
	'white rose',
)

NOTES_SUBSTITUTIONS = {
	'2 albino salamanders': 'albino salamander',
	'2 red mushroom': 'red mushroom',
	'albino salamanders': 'albino salamander',
	'red mushrooms': 'red mushroom',
	'apples': 'apple',
	'eggs': 'egg',
	'2x ': '',
	'3x ': '',
	' \\(2x\\)': '',
	' \\(3x\\)': '',
	' 2x': '',
	' 3x': '',
	' x2': '',
	' x3': '',
	'ash arrow\\(s\\)': 'ash arrows',
	'belladonna berries': 'belladonna',
	'blackberry': 'blackberries',
	'bluberries': 'blueberries',
	'block flower': 'blackflower',
	'clover blackberries': 'clover, blackberries',
	'clover herb:': 'clover,',
	'darkfloower': 'darkflower',
	'dark green moss': 'dark-green moss',
	'green sickly': 'sickly green mushroom',
	'hawthorn tree': 'hawthorn berries',
	'herb: ': '',
	'valerian root': 'valerian',
	'inkcap albino salamander': 'inkcap, albino salamander',
	'lilly': 'lily',
	'oil flask': 'oil',
	'oil flasks': 'oil',
	'oil lantern': 'oil, lantern',
	'oils': 'oil',
	'patch of moss': 'moss',
	'fosforescent': 'phosphorescent',
	'phosporescent': 'phosphorescent',
	'raspberry blueberry': 'raspberries, blueberries',
	'raspberry nettle': 'raspberries, nettle',
	'reed pipes': 'reed',
	'water skin': 'waterskin',
	'wooden traveller\'s cloak': 'woollen traveller\'s cloak',
	'reed tainted water': 'reed, tainted water',
	'water lily': 'water-lily',
	'use pickuse pick': 'use pick',
	'wood anemone': 'anemone',
	'raspberries nettle': 'raspberries, nettle',
	'tarragon foxglove belladonna': 'tarragon, foxglove, belladonna',
}